# Generated by Django 3.2 on 2021-04-09 05:29

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a city name', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', django.contrib.gis.db.models.fields.PointField(blank=True, srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter a place name', max_length=100)),
                ('description', models.CharField(help_text='Enter a place description', max_length=500)),
                ('phone', models.CharField(help_text='Enter a phone number', max_length=10)),
                ('type_of_place', models.CharField(choices=[('a', 'Park'), ('b', 'Restaurant'), ('c', 'Mall'), ('d', 'Amusement park'), ('e', 'Museum'), ('f', 'Beach'), ('g', 'Theater'), ('h', 'Lodge'), ('i', 'Others')], default='m', help_text='Place Type', max_length=1)),
                ('address', models.CharField(help_text='Enter a place address', max_length=250)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='placeapp.city')),
                ('location', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='placeapp.location')),
            ],
        ),
    ]
