# Generated by Django 3.2 on 2021-04-09 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placeapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='name',
            field=models.CharField(default='', help_text='Enter a place name', max_length=100),
            preserve_default=False,
        ),
    ]
